variables:
  MUMBLE_ENVIRONMENT_STORE: '$(Agent.ToolsDirectory)/MumbleBuild'
  MUMBLE_ENVIRONMENT_SOURCE: 'https://dl.mumble.info/build/vcpkg'
  MUMBLE_ENVIRONMENT_PATH: '$(MUMBLE_ENVIRONMENT_STORE)/$(MUMBLE_ENVIRONMENT_VERSION)'
  MUMBLE_ENVIRONMENT_TOOLCHAIN: '$(MUMBLE_ENVIRONMENT_PATH)/scripts/buildsystems/vcpkg.cmake'

jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    variables:
      MUMBLE_ENVIRONMENT_VERSION: 'win64-static-1.4.x-2020-05-27-ecb3c64-1151'
    steps:
    - template: steps_windows.yml
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: steps_linux.yml
  - job: macOS
    pool:
      vmImage: 'macOS-latest'
    variables:
      MUMBLE_ENVIRONMENT_VERSION: 'macos-static-1.4.x-2020-05-27-ecb3c64-1151'
    steps:
    - template: steps_macos.yml
      parameters:
        installEnvironment: true
  - job: Translations
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: .ci/azure-pipelines/install-environment_linux_translations.bash
      displayName: 'Install Qt tools'
    - script: .ci/azure-pipelines/assertNoTranslationChanges.sh
      displayName: 'Checking for translation changes'
