steps:
  - script: git submodule --quiet update --init --recursive
    displayName: 'Fetch submodules'
  - template: task-environment-cache.yml
  - powershell: .ci/azure-pipelines/install-environment_windows.ps1
    displayName: 'Install build environment'
  - script: .ci/azure-pipelines/build_windows.bat
    displayName: 'Build'
  - powershell: |
      cd $(Build.BinariesDirectory)
      .\Create-Win32InstallerMUI.ps1 -PackageName 'Mumble_${{parameters.arch}}' -Version '1.4.0'
      cp *.sha* $(Build.ArtifactStagingDirectory)
      cp *.msi $(Build.ArtifactStagingDirectory)
      7z a PDBs.7z *.pdb 
      cp PDBs.7z $(Build.ArtifactStagingDirectory)
    displayName: Build installer
  - template: task-publish-artifacts.yml
    parameters:
      name: 'Windows (${{parameters.arch}}) installer'
